packages:
  - .

confirmModulesPurge: false

overrides:
  hono: 4.12.25
  esbuild: 0.25.12
  postcss: 8.5.10

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
